name: beclust3d
channels:
  - defaults
  - conda-forge
dependencies:
  - biopandas=0.5.1
  - biopython=1.78
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - contourpy=1.3.1
  - cycler=0.11.0
  - docutils=0.18.1
  - exceptiongroup=1.2.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - gettext=0.21.0
  - icu=73.1
  - idna=3.7
  - iniconfig=1.1.1
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - libxml2=2.13.5
  - llvm-openmp=14.0.6
  - looseversion=1.3.0
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - mmtf-python=1.1.3
  - msgpack-python=1.0.3
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.16
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=2.12
  - pcre2=10.42
  - pillow=11.1.0
  - pip=25.0
  - pluggy=1.5.0
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - pytest=8.3.4
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - pytz=2024.1
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - setuptools=75.8.0
  - six=1.17.0
  - sqlite=3.45.3
  - statistics=1.0.3.5
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.4.2
  - tzdata=2025a
  - unicodedata2=15.1.0
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - dsspparser==0.1.3
      - pyyaml==6.0.3
      - wget==3.2
